tap "homebrew/bundle"
tap "jordond/tap"
tap "nikitabobko/tap"
tap "tw93/tap"
brew "aichat"
brew "antidote"
brew "brotli"
brew "astroterm"
brew "btop"
brew "carthage"
brew "cloudflared"
brew "cmake"
brew "coreutils"
brew "curl"
brew "curlie"
brew "direnv"
brew "displayplacer"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "findutils"
brew "flyctl"
brew "fx"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "glow"
brew "helix"
brew "jq"
brew "lazygit"
brew "libimobiledevice"
brew "lua"
brew "macmon"
brew "mosh"
brew "neovim"
brew "qt"
brew "gnuplot"
brew "dockutil"
brew "go"
brew "gum"
brew "htop"
brew "mackup"
brew "mas"
brew "mcfly"
brew "moreutils"
brew "navi"
brew "node"
brew "openjdk"
brew "python@3.11"
brew "python@3.12"
brew "ruby"
brew "subversion"
brew "tailscale"
brew "thefuck"
brew "tldr", link: false
brew "tlrc"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "yt-dlp"
brew "zoxide"
brew "zsh"
brew "zsh-completions"
brew "jordond/tap/jolt"
brew "tw93/tap/mole"
cask "1password"
cask "1password-cli"
cask "brightintosh"
cask "codex"
cask "eagle"
cask "granola"
cask "handbrake-app"
cask "json-viewer"
cask "logi-options+"
cask "nikitabobko/tap/aerospace"
cask "alcove"
cask "android-platform-tools"
cask "bezel"
cask "bambu-studio"
cask "beeper"
cask "bike"
cask "blender"
cask "choosy"
cask "claude"
cask "cleanshot"
cask "cloudytabs"
cask "contexts"
cask "cursor"
cask "plex-media-server"
cask "qlmarkdown"
cask "slack"
cask "tailscale-app"
cask "thebrowsercompany-dia"
cask "figma"
cask "framer"
cask "ghostty"
cask "google-chrome"
cask "handbrake"
cask "iina"
cask "itsycal"
cask "jdownloader"
cask "karabiner-elements"
cask "keyclu"
cask "libreoffice"
cask "lm-studio"
cask "mp3tag"
cask "logi-options+"
cask "lunar"
cask "nicotine-plus"
cask "notion"
cask "notion-calendar"
cask "ogdesign-eagle"
cask "obsidian"
cask "opal-composer"
cask "origami-studio"
cask "postman"
cask "qlvideo"
cask "raindropio"
cask "raspberry-pi-imager"
cask "raycast"
cask "replacicon"
cask "rive"
cask "rocket"
cask "screen-studio"
cask "sf-symbols"
cask "soulseek"
cask "spline"
cask "spotify"
cask "steam"
cask "tor-browser"
cask "transmission"
cask "typeface"
cask "vnc-viewer"
cask "voiceink"
cask "warp"
cask "whyfi"
cask "zed"
cask "nordvpn"
mas " Eagle for Safari     ", id: 1526651672
mas " Minimal Twitter      ", id: 1668204600
mas " Save to Raindrop.io  ", id: 1549370672
mas " WhatFont             ", id: 1437138382
mas "1Password for Safari ", id: 1569813296
mas "Balatro", id: 6502451661
mas "BrightIntosh", id: 6452471855
mas "Flighty", id: 1358823008
mas "iMovie", id: 408981434
mas "Infuse", id: 1136220934
mas "JSONPeep", id: 1458969831
mas "Klack", id: 6446206067
mas "mymind", id: 1532801185
mas "Pieoneer", id: 6739781207
mas "Plug", id: 1514182074
mas "Shazam", id: 897118787
mas "Slack", id: 803453959
mas "TestFlight", id: 899247664
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Unsplash Wallpapers", id: 1284863847
mas "Wipr", id: 1662217862
mas "Xcode", id: 497799835
vscode "1password.op-vscode"
vscode "alefragnani.project-manager"
vscode "apvarun.celestial"
vscode "astro-build.astro-vscode"
vscode "atelierbram.atelier-vscode-themes"
vscode "austenc.tailwind-docs"
vscode "aykutsarac.jsoncrack-vscode"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.npm-intellisense"
vscode "christian-kohler.path-intellisense"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "dbaeumer.vscode-eslint"
vscode "dsznajder.es7-react-js-snippets"
vscode "ecmel.vscode-html-css"
vscode "eliverlara.andromeda"
vscode "esbenp.prettier-vscode"
vscode "figma.figma-vscode-extension"
vscode "formulahendry.code-runner"
vscode "formulahendry.terminal"
vscode "github.remotehub"
vscode "heybourn.headwind"
vscode "idleberg.applescript"
vscode "ionutvmi.path-autocomplete"
vscode "mikestead.dotenv"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.remote-repositories"
vscode "nash.awesome-flutter-snippets"
vscode "openai.openai-chatgpt-adhoc"
vscode "oscarcs.dart-syntax-highlighting-only"
vscode "pkief.material-icon-theme"
vscode "seansassenrath.vscode-theme-superonedark"
vscode "stripe.markdoc-language-support"
vscode "sumneko.lua"
vscode "tomoki1207.pdf"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "wicked-labs.wvsc-serendipity"
go "github.com/danielmiessler/fabric"
